Fix Sonar Cloud Code smell for EasyInput
giorgosart/react-easy-edit pull request #195
Opened 2023-10-27 07:29 UTC by kareemmahlees

closes #182

2023-10-27 07:30 UTC, kareemmahlees commented
@giorgosart could you review?

2023-10-27 10:28 UTC, giorgosart requested changes
@kareemmahlees I think that you need to add `onfocus: PropTypes.func` in the propTypes section and leave the `onfocus: () => { }` in defaultProps

2023-10-27 11:50 UTC, kareemmahlees commented
> @kareemmahlees I think that you need to add `onfocus: PropTypes.func` in the propTypes section and leave the `onfocus: () => { }` in defaultProps

but the code smell indicates that the error is in the default props!

2023-10-27 22:22 UTC, giorgosart commented
@kareemmahlees [defaultProp "onfocus" has no corresponding propTypes declaration.](https://sonarcloud.io/project/issues?open=AYsB72jgWgZgXcKLGRMB&id=giorgosart_react-easy-edit) this states that a prop that has a default value for it is not declared in propsTypes.

2023-10-28 11:31 UTC, kareemmahlees commented
@giorgosart done!

2023-10-28 22:47 UTC, giorgosart reviewed
@kareemmahlees see my latest comments.

2023-10-28 22:47 UTC, giorgosart commented on src/lib/EasyInput.jsx
> +  onfocus: PropTypes.func
remove this line

2023-10-28 22:47 UTC, giorgosart commented on src/lib/EasyInput.jsx
> +  onfocus: ()=>{}
```suggestion
  onFocus: ()=>{}
```

2023-11-02 19:58 UTC, giorgosart commented on src/lib/EasyInput.jsx
> +  onfocus: PropTypes.func
```suggestion
```

2023-11-02 19:59 UTC, giorgosart commented on src/lib/EasyInput.jsx
> +  onBlur: PropTypes.func,
```suggestion
  onBlur: PropTypes.func
```

2023-11-02 20:02 UTC, giorgosart approved these changes

2023-11-02 20:02 UTC, merged